[package]
name = "crypto_playpen"
version = "0.1.0"
authors = ["Philip Robinson <simian@tari.com>"]
edition = "2018"

[dependencies]
crypto = { git = 'https://github.com/tari-project/tari/', branch = "development" }
rand = "0.5.5"